from typing import Any

class LooseVersion:
    vstring: str
    version: tuple[Any, ...]
    def __init__(self, vstring: str = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
